version: "3.3"

services:

  envoy:
    platform: "linux/x86_64"
    image: "envoyproxy/envoy:v1.20.6"
    container_name: "envoy"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml"

  httpbin:
    platform: "linux/x86_64"
    image: "kennethreitz/httpbin"
    container_name: "httpbin"

  echo:
    platform: "linux/x86_64"
    image: "ealen/echo-server:latest"
    container_name: "echo"